In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X=iris.data

In [7]:
y=iris.target

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from keras.utils import to_categorical

In [11]:
y = to_categorical(y)

In [12]:
y.shape

(150, 3)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train.shape

(100, 4)

In [15]:
X_test.shape

(50, 4)

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler_object = MinMaxScaler()
scaler_object.fit(X_train)
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [17]:
X_train.max()

7.7

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [19]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(scaled_X_train,y_train,epochs=150, verbose=2)

Epoch 1/150
4/4 - 0s - loss: 1.0628 - accuracy: 0.4000 - 421ms/epoch - 105ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0557 - accuracy: 0.4700 - 7ms/epoch - 2ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0482 - accuracy: 0.5000 - 10ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0410 - accuracy: 0.6200 - 14ms/epoch - 4ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0337 - accuracy: 0.6400 - 9ms/epoch - 2ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0266 - accuracy: 0.6500 - 8ms/epoch - 2ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0193 - accuracy: 0.6500 - 5ms/epoch - 1ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0127 - accuracy: 0.6500 - 7ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0058 - accuracy: 0.6500 - 4ms/epoch - 1ms/step
Epoch 10/150
4/4 - 0s - loss: 0.9985 - accuracy: 0.6500 - 5ms/epoch - 1ms/step
Epoch 11/150
4/4 - 0s - loss: 0.9914 - accuracy: 0.6500 - 6ms/epoch - 1ms/step
Epoch 12/150
4/4 - 0s - loss: 0.9845 - accuracy: 0.6500 - 6ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 0.9776 - accuracy: 0.6500

4/4 - 0s - loss: 0.4376 - accuracy: 0.8800 - 5ms/epoch - 1ms/step
Epoch 105/150
4/4 - 0s - loss: 0.4353 - accuracy: 0.8900 - 4ms/epoch - 1000us/step
Epoch 106/150
4/4 - 0s - loss: 0.4333 - accuracy: 0.8900 - 6ms/epoch - 2ms/step
Epoch 107/150
4/4 - 0s - loss: 0.4311 - accuracy: 0.9000 - 5ms/epoch - 1ms/step
Epoch 108/150
4/4 - 0s - loss: 0.4290 - accuracy: 0.9000 - 3ms/epoch - 751us/step
Epoch 109/150
4/4 - 0s - loss: 0.4270 - accuracy: 0.9000 - 4ms/epoch - 999us/step
Epoch 110/150
4/4 - 0s - loss: 0.4247 - accuracy: 0.9000 - 3ms/epoch - 750us/step
Epoch 111/150
4/4 - 0s - loss: 0.4223 - accuracy: 0.9000 - 6ms/epoch - 1ms/step
Epoch 112/150
4/4 - 0s - loss: 0.4202 - accuracy: 0.9000 - 4ms/epoch - 1000us/step
Epoch 113/150
4/4 - 0s - loss: 0.4181 - accuracy: 0.9000 - 4ms/epoch - 1ms/step
Epoch 114/150
4/4 - 0s - loss: 0.4163 - accuracy: 0.9000 - 6ms/epoch - 1ms/step
Epoch 115/150
4/4 - 0s - loss: 0.4147 - accuracy: 0.9100 - 4ms/epoch - 1000us/step
Epoch 116/150
4/4 - 0s - loss: 0.4119 -

In [22]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 2ms/step


array([[1.5962733e-02, 4.8700795e-01, 4.9702942e-01],
       [9.7608578e-01, 2.2528104e-02, 1.3862117e-03],
       [1.6374164e-04, 1.1666704e-01, 8.8316923e-01],
       [2.2484919e-02, 5.2818531e-01, 4.4932982e-01],
       [5.0032362e-03, 3.6465219e-01, 6.3034457e-01],
       [9.5663512e-01, 4.0651426e-02, 2.7134672e-03],
       [1.1613947e-01, 6.5694022e-01, 2.2692034e-01],
       [2.9644785e-03, 2.9981580e-01, 6.9721979e-01],
       [5.4355999e-03, 4.1256493e-01, 5.8199942e-01],
       [4.2685024e-02, 6.1763585e-01, 3.3967915e-01],
       [8.3141243e-03, 3.9493960e-01, 5.9674627e-01],
       [9.5404547e-01, 4.3033499e-02, 2.9210902e-03],
       [9.7470707e-01, 2.3898870e-02, 1.3939968e-03],
       [9.5687014e-01, 4.0424496e-02, 2.7053517e-03],
       [9.8949569e-01, 9.9618789e-03, 5.4249808e-04],
       [2.9428495e-02, 5.3928787e-01, 4.3128362e-01],
       [1.8526131e-03, 2.4054100e-01, 7.5760645e-01],
       [3.7083965e-02, 6.0920572e-01, 3.5371029e-01],
       [2.9558972e-02, 5.574

In [23]:
model.metrics_names

['loss', 'accuracy']

In [24]:
model.evaluate(x=scaled_X_test,y=y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.3134 - accuracy: 0.9200


[0.3133724331855774, 0.9200000166893005]

In [25]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

predictions = np.argmax(model.predict(scaled_X_test), axis=-1)

2/2 [==============================] - 0s 2ms/step


In [26]:
predictions

array([2, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [27]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [31]:
print(confusion_matrix(y_test.argmax(axis=1),predictions))

[[19  0  0]
 [ 0 11  4]
 [ 0  0 16]]


In [29]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.73      0.85        15
           2       0.80      1.00      0.89        16

    accuracy                           0.92        50
   macro avg       0.93      0.91      0.91        50
weighted avg       0.94      0.92      0.92        50



In [30]:
print(accuracy_score(y_test.argmax(axis=1),predictions))

0.92
